/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'home-banner-slides': HomeBannerSlide;
    'tour-packages': TourPackage;
    'explore-banner-slides': ExploreBannerSlide;
    'explore-listings': ExploreListing;
    'itineraries-banner-slides': ItinerariesBannerSlide;
    'package-banner-slides': PackageBannerSlide;
    'blog-categories': BlogCategory;
    destinations: Destination;
    excursions: Excursion;
    itineraries: Itinerary;
    'blog-posts': BlogPost;
    'gallery-items': GalleryItem;
    testimonials: Testimonial;
    bloggers: Blogger;
    'media-banners': MediaBanner;
    'payload-kv': PayloadKv;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'home-banner-slides': HomeBannerSlidesSelect<false> | HomeBannerSlidesSelect<true>;
    'tour-packages': TourPackagesSelect<false> | TourPackagesSelect<true>;
    'explore-banner-slides': ExploreBannerSlidesSelect<false> | ExploreBannerSlidesSelect<true>;
    'explore-listings': ExploreListingsSelect<false> | ExploreListingsSelect<true>;
    'itineraries-banner-slides': ItinerariesBannerSlidesSelect<false> | ItinerariesBannerSlidesSelect<true>;
    'package-banner-slides': PackageBannerSlidesSelect<false> | PackageBannerSlidesSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    excursions: ExcursionsSelect<false> | ExcursionsSelect<true>;
    itineraries: ItinerariesSelect<false> | ItinerariesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'gallery-items': GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    bloggers: BloggersSelect<false> | BloggersSelect<true>;
    'media-banners': MediaBannersSelect<false> | MediaBannersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Hero banner slider images on the home page. Add, remove or reorder slides here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-banner-slides".
 */
export interface HomeBannerSlide {
  id: number;
  /**
   * e.g. "Moscow Winter", "St. Petersburg Canals"
   */
  title: string;
  /**
   * Upload the image directly. Recommended size: 1920×1080px.
   */
  image?: (number | null) | Media;
  /**
   * Paste an external URL if not uploading. Takes priority over uploaded image.
   */
  imageUrl?: string | null;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Expanding destination cards on the home page hero section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-packages".
 */
export interface TourPackage {
  id: number;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Use this if image is hosted externally. Overrides uploaded image.
   */
  imageUrl?: string | null;
  link?: string | null;
  featured?: boolean | null;
  /**
   * Lower numbers appear first (left to right).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Background slider images for the Explore page hero banner. Add, remove or reorder slides here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "explore-banner-slides".
 */
export interface ExploreBannerSlide {
  id: number;
  /**
   * e.g. "Moscow Winter", "Sochi Beach"
   */
  title: string;
  image?: (number | null) | Media;
  /**
   * Paste an external URL if not uploading. Takes priority over uploaded image.
   */
  imageUrl?: string | null;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The destination cards shown on the Explore page grid. Each card links to its city excursion detail page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "explore-listings".
 */
export interface ExploreListing {
  id: number;
  /**
   * Card title shown on the Explore page — e.g. "Moscow", "Sochi".
   */
  destinationName: string;
  /**
   * URL or page this card links to — e.g. "murmansk-excursions.html" or "https://example.com".
   */
  destinationSlug?: string | null;
  image?: (number | null) | Media;
  /**
   * External image URL — takes priority over uploaded image.
   */
  imageUrl?: string | null;
  /**
   * Paragraph shown on the Home page card when hovering. e.g. "Above the Arctic Circle, Murmansk delivers…"
   */
  description?: string | null;
  /**
   * Check to show this city in the "Top Destination" section on the home page.
   */
  homeFeature?: boolean | null;
  active?: boolean | null;
  /**
   * Lower = appears first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Banner slider images on the Popular Itineraries page. Add, remove or reorder slides here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itineraries-banner-slides".
 */
export interface ItinerariesBannerSlide {
  id: number;
  /**
   * e.g. "Moscow Winter", "Sochi Beach" — only shown in the CMS, not on the page.
   */
  title: string;
  /**
   * Upload the image directly. Recommended size: 1920×1080px.
   */
  image?: (number | null) | Media;
  /**
   * Paste an external URL instead of uploading. Takes priority over uploaded image.
   */
  imageUrl?: string | null;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Banner slider images for individual package/tour detail pages. One collection shared across all packages — filter by Package Slug.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "package-banner-slides".
 */
export interface PackageBannerSlide {
  id: number;
  /**
   * e.g. "Moscow Kremlin" — only shown in the CMS admin, never on the page.
   */
  title: string;
  /**
   * Must match the slug used in the page CMS loader. e.g. "moscow-spb", "murmansk-moscow", "sochi".
   */
  packageSlug: string;
  /**
   * Recommended size: 1920×1080px.
   */
  image?: (number | null) | Media;
  /**
   * Paste an external URL instead of uploading. Takes priority over uploaded image.
   */
  imageUrl?: string | null;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog tabs shown on the Media page. Add, rename or reorder tabs here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  /**
   * e.g. "About New Packages", "Travel Tips"
   */
  name: string;
  /**
   * Auto-generated from the Tab Label. Blog posts with this slug in their Category field appear under this tab.
   */
  slug?: string | null;
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cities / destinations. Adding a city here makes it available in the Explore Details "City Page" dropdown.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  /**
   * e.g. "Kamchatka", "Yekaterinburg" — slug and excursion slug are auto-generated.
   */
  title: string;
  slug?: string | null;
  /**
   * Auto-generated as "{city}-excursions". Only edit if your HTML page uses a different slug.
   */
  excursionPageSlug?: string | null;
  heroImage?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  thumbnailImage?: (number | null) | Media;
  homeFeature?: boolean | null;
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual excursion flip-cards shown on each city's excursion detail page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "excursions".
 */
export interface Excursion {
  id: number;
  title: string;
  /**
   * Select the city this excursion belongs to. Add new cities in Explore Listings.
   */
  cityPage?: (number | null) | ExploreListing;
  /**
   * e.g. "Moscow, Russia"
   */
  location?: string | null;
  /**
   * e.g. "4 Hours"
   */
  duration?: string | null;
  startTour?: string | null;
  transportation?: string | null;
  image?: (number | null) | Media;
  /**
   * External URL — takes priority over uploaded image.
   */
  imageUrl?: string | null;
  /**
   * Text shown on the card back when "View Details" is clicked.
   */
  description?: string | null;
  order?: number | null;
  active?: boolean | null;
  destinationSlug?: string | null;
  destinationTitle?: string | null;
  homeFeature?: boolean | null;
  destinationOrder?: number | null;
  destinationHeroImage?: string | null;
  destinationDescription?: string | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  destinationImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tour packages — controls both the Popular Itineraries listing cards AND the full detail pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itineraries".
 */
export interface Itinerary {
  id: number;
  title: string;
  /**
   * Must match the HTML filename. e.g. slug "moscow-spb-tour" → moscow-spb-tour.html
   */
  slug?: string | null;
  image?: (number | null) | Media;
  /**
   * Use if not uploading. Shows on the Popular Itineraries listing cards.
   */
  imageUrl?: string | null;
  duration?: string | null;
  price?: string | null;
  featured?: boolean | null;
  order?: number | null;
  heroBadge?: string | null;
  /**
   * Shown as the large H1 on the detail page banner.
   */
  heroTitle?: string | null;
  priceDouble?: string | null;
  /**
   * Leave blank if not applicable.
   */
  priceSingle?: string | null;
  /**
   * e.g. "Moscow: Holiday Inn 4★ | Saint Petersburg: Park Inn Radisson 4★"
   */
  hotelNotes?: string | null;
  /**
   * Add one entry per day. Each day can have a description and optional highlight callouts.
   */
  itinerary?:
    | {
        day: number;
        title: string;
        /**
         * Main paragraph text for the day.
         */
        description?: string | null;
        /**
         * Special callout boxes within the day (e.g. museum visits, transport info).
         */
        highlights?:
          | {
              /**
               * Browse icons at remixicon.com
               */
              icon?: string | null;
              boldText?: string | null;
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  inclusions?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        /**
         * Use if not uploading.
         */
        imageUrl?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog cards shown in the four-tab blog section on the Media page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  excerpt: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  /**
   * Select the tab this post belongs to.
   */
  category: string;
  /**
   * Auto-set to today. Change if needed.
   */
  publishedDate?: string | null;
  author?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Image cards shown in the gallery swiper carousel on the Media page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items".
 */
export interface GalleryItem {
  id: number;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Controls carousel order (lower = earlier).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reviews shown in the testimonial swiper on the Media page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  author: string;
  role?: string | null;
  image?: (number | null) | Media;
  rating?: number | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blogger review cards with play-button shown on the Media page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bloggers".
 */
export interface Blogger {
  id: number;
  name: string;
  role?: string | null;
  image?: (number | null) | Media;
  /**
   * Paste a YouTube link or select an uploaded video from the media library.
   */
  videoUrl?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hero banner content for each inner page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-banners".
 */
export interface MediaBanner {
  id: number;
  page:
    | 'popular-itineraries'
    | 'media'
    | 'golden-ring'
    | 'murmansk-excursions'
    | 'kazan-excursions'
    | 'sochi-excursions'
    | 'saint-petersburg-excursions'
    | 'moscow-excursions'
    | 'moscow'
    | 'saint-petersburg'
    | 'murmansk'
    | 'sochi'
    | 'kazan'
    | 'lake-baikal'
    | 'kamchatka'
    | 'nizhny-novgorod';
  title: string;
  titleHighlight?: string | null;
  subtitle?: string | null;
  description?: string | null;
  backgroundImage?: (number | null) | Media;
  slides?:
    | {
        image: number | Media;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-banner-slides_select".
 */
export interface HomeBannerSlidesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  imageUrl?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-packages_select".
 */
export interface TourPackagesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  imageUrl?: T;
  link?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "explore-banner-slides_select".
 */
export interface ExploreBannerSlidesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  imageUrl?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "explore-listings_select".
 */
export interface ExploreListingsSelect<T extends boolean = true> {
  destinationName?: T;
  destinationSlug?: T;
  image?: T;
  imageUrl?: T;
  description?: T;
  homeFeature?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itineraries-banner-slides_select".
 */
export interface ItinerariesBannerSlidesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  imageUrl?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "package-banner-slides_select".
 */
export interface PackageBannerSlidesSelect<T extends boolean = true> {
  title?: T;
  packageSlug?: T;
  image?: T;
  imageUrl?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excursionPageSlug?: T;
  heroImage?: T;
  description?: T;
  image?: T;
  thumbnailImage?: T;
  homeFeature?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "excursions_select".
 */
export interface ExcursionsSelect<T extends boolean = true> {
  title?: T;
  cityPage?: T;
  location?: T;
  duration?: T;
  startTour?: T;
  transportation?: T;
  image?: T;
  imageUrl?: T;
  description?: T;
  order?: T;
  active?: T;
  destinationSlug?: T;
  destinationTitle?: T;
  homeFeature?: T;
  destinationOrder?: T;
  destinationHeroImage?: T;
  destinationDescription?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  destinationImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itineraries_select".
 */
export interface ItinerariesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  imageUrl?: T;
  duration?: T;
  price?: T;
  featured?: T;
  order?: T;
  heroBadge?: T;
  heroTitle?: T;
  priceDouble?: T;
  priceSingle?: T;
  hotelNotes?: T;
  itinerary?:
    | T
    | {
        day?: T;
        title?: T;
        description?: T;
        highlights?:
          | T
          | {
              icon?: T;
              boldText?: T;
              text?: T;
              id?: T;
            };
        id?: T;
      };
  inclusions?:
    | T
    | {
        text?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        alt?: T;
        id?: T;
      };
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  image?: T;
  category?: T;
  publishedDate?: T;
  author?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  image?: T;
  rating?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bloggers_select".
 */
export interface BloggersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  image?: T;
  videoUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-banners_select".
 */
export interface MediaBannersSelect<T extends boolean = true> {
  page?: T;
  title?: T;
  titleHighlight?: T;
  subtitle?: T;
  description?: T;
  backgroundImage?: T;
  slides?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}