// Auto-generated initial schema migration
export async function up({ payload }) {
  const db = payload.db
  const statements = [
  "CREATE TABLE `blog_categories` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`slug` text,\n\t`order` numeric DEFAULT 0,\n\t`active` integer DEFAULT true,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE TABLE `blog_posts` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`excerpt` text NOT NULL,\n\t`content` text,\n\t`image_id` integer,\n\t`category` text NOT NULL,\n\t`published_date` text,\n\t`author` text,\n\t`featured` integer DEFAULT false,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `bloggers` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`role` text,\n\t`image_id` integer,\n\t`video_url` text,\n\t`order` numeric DEFAULT 0,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE \"destinations\" (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`slug` text,\n\t`excursion_page_slug` text,\n\t`hero_image` text,\n\t`description` text,\n\t`image_id` integer,\n\t`thumbnail_image_id` integer,\n\t`home_feature` integer DEFAULT false,\n\t`order` numeric DEFAULT 0,\n\t`active` integer DEFAULT true,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`thumbnail_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE \"excursions\" (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`city_page_id` integer,\n\t`location` text,\n\t`duration` text,\n\t`start_tour` text DEFAULT 'Your Hotel',\n\t`transportation` text DEFAULT 'By Cab',\n\t`image_id` integer,\n\t`image_url` text,\n\t`description` text,\n\t`order` numeric DEFAULT 0,\n\t`active` integer DEFAULT true,\n\t`destination_slug` text,\n\t`destination_title` text DEFAULT 'Unknown',\n\t`home_feature` integer DEFAULT false,\n\t`destination_order` numeric DEFAULT 0,\n\t`destination_hero_image` text,\n\t`destination_description` text,\n\t`destination_image_id` integer,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`city_page_id`) REFERENCES `explore_listings`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`destination_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `excursions_highlights` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`text` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `excursions`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `explore_banner_slides` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`image_id` integer,\n\t`image_url` text,\n\t`order` numeric DEFAULT 0,\n\t`active` integer DEFAULT true,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE \"explore_listings\" (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`destination_name` text NOT NULL,\n\t`destination_slug` text,\n\t`image_id` integer,\n\t`image_url` text,\n\t`order` numeric DEFAULT 0,\n\t`active` integer DEFAULT true,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL, `description` text, `home_feature` integer DEFAULT false,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `gallery_items` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text,\n\t`image_id` integer,\n\t`order` numeric DEFAULT 0,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `home_banner_slides` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`image_id` integer,\n\t`image_url` text,\n\t`order` numeric DEFAULT 0,\n\t`active` integer DEFAULT true,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE \"itineraries\" (\n    id           INTEGER PRIMARY KEY NOT NULL,\n    title        TEXT    NOT NULL,\n    slug         TEXT,\n    image_id     INTEGER,\n    image_url    TEXT,\n    duration     TEXT,\n    price        TEXT,\n    description  TEXT,\n    featured     INTEGER DEFAULT false,\n    \"order\"      NUMERIC DEFAULT 0,\n    hero_badge   TEXT,\n    hero_title   TEXT,\n    price_double TEXT,\n    price_single TEXT,\n    hotel_notes  TEXT,\n    updated_at   TEXT    DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n    created_at   TEXT    DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n    FOREIGN KEY (image_id) REFERENCES media(id) ON UPDATE no action ON DELETE set null\n  )",
  "CREATE TABLE `itineraries_banner_slides` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`image_id` integer,\n\t`image_url` text,\n\t`order` numeric DEFAULT 0,\n\t`active` integer DEFAULT true,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE itineraries_gallery (\n      _order     INTEGER NOT NULL,\n      _parent_id INTEGER NOT NULL REFERENCES itineraries(id) ON DELETE CASCADE,\n      id         TEXT    NOT NULL PRIMARY KEY,\n      image_id   INTEGER REFERENCES media(id) ON DELETE SET NULL,\n      image_url  TEXT,\n      alt        TEXT\n    )",
  "CREATE TABLE itineraries_inclusions (\n      _order     INTEGER NOT NULL,\n      _parent_id INTEGER NOT NULL REFERENCES itineraries(id) ON DELETE CASCADE,\n      id         TEXT    NOT NULL PRIMARY KEY,\n      \"text\"     TEXT    NOT NULL\n    )",
  "CREATE TABLE `itineraries_itinerary` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`day` numeric NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `itineraries`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE \"itineraries_itinerary_highlights\" (\n\t`_order` integer NOT NULL,\n\t`_parent_id` text NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`icon` text,\n\t`bold_text` text,\n\t`text` text,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `itineraries_itinerary`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `media` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`alt` text NOT NULL,\n\t`caption` text,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`url` text,\n\t`thumbnail_u_r_l` text,\n\t`filename` text,\n\t`mime_type` text,\n\t`filesize` numeric,\n\t`width` numeric,\n\t`height` numeric,\n\t`focal_x` numeric,\n\t`focal_y` numeric,\n\t`sizes_thumbnail_url` text,\n\t`sizes_thumbnail_width` numeric,\n\t`sizes_thumbnail_height` numeric,\n\t`sizes_thumbnail_mime_type` text,\n\t`sizes_thumbnail_filesize` numeric,\n\t`sizes_thumbnail_filename` text,\n\t`sizes_card_url` text,\n\t`sizes_card_width` numeric,\n\t`sizes_card_height` numeric,\n\t`sizes_card_mime_type` text,\n\t`sizes_card_filesize` numeric,\n\t`sizes_card_filename` text,\n\t`sizes_hero_url` text,\n\t`sizes_hero_width` numeric,\n\t`sizes_hero_height` numeric,\n\t`sizes_hero_mime_type` text,\n\t`sizes_hero_filesize` numeric,\n\t`sizes_hero_filename` text\n)",
  "CREATE TABLE `media_banners` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`page` text NOT NULL,\n\t`title` text NOT NULL,\n\t`title_highlight` text,\n\t`subtitle` text,\n\t`description` text,\n\t`background_image_id` integer,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`background_image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `media_banners_slides` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`image_id` integer NOT NULL,\n\t`image_url` text,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `media_banners`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `package_banner_slides` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`package_slug` text NOT NULL,\n\t`image_id` integer,\n\t`image_url` text,\n\t`order` numeric DEFAULT 0,\n\t`active` integer DEFAULT true,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `payload_kv` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`key` text NOT NULL,\n\t`data` text NOT NULL\n)",
  "CREATE TABLE `payload_migrations` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text,\n\t`batch` numeric,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE TABLE `payload_preferences` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`key` text,\n\t`value` text,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL\n)",
  "CREATE TABLE `payload_preferences_rels` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`order` integer,\n\t`parent_id` integer NOT NULL,\n\t`path` text NOT NULL,\n\t`users_id` integer,\n\tFOREIGN KEY (`parent_id`) REFERENCES `payload_preferences`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`users_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE TABLE `testimonials` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`quote` text NOT NULL,\n\t`author` text NOT NULL,\n\t`role` text,\n\t`image_id` integer,\n\t`rating` numeric DEFAULT 5,\n\t`featured` integer DEFAULT true,\n\t`order` numeric DEFAULT 0,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `tour_packages` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`title` text NOT NULL,\n\t`description` text,\n\t`image_id` integer,\n\t`image_url` text,\n\t`link` text,\n\t`featured` integer DEFAULT true,\n\t`order` numeric DEFAULT 0,\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\tFOREIGN KEY (`image_id`) REFERENCES `media`(`id`) ON UPDATE no action ON DELETE set null\n)",
  "CREATE TABLE `users` (\n\t`id` integer PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`role` text DEFAULT 'editor',\n\t`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,\n\t`email` text NOT NULL,\n\t`reset_password_token` text,\n\t`reset_password_expiration` text,\n\t`salt` text,\n\t`hash` text,\n\t`login_attempts` numeric DEFAULT 0,\n\t`lock_until` text\n)",
  "CREATE TABLE `users_sessions` (\n\t`_order` integer NOT NULL,\n\t`_parent_id` integer NOT NULL,\n\t`id` text PRIMARY KEY NOT NULL,\n\t`created_at` text,\n\t`expires_at` text NOT NULL,\n\tFOREIGN KEY (`_parent_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\n)",
  "CREATE INDEX `blog_categories_created_at_idx` ON `blog_categories` (`created_at`)",
  "CREATE UNIQUE INDEX `blog_categories_slug_idx` ON `blog_categories` (`slug`)",
  "CREATE INDEX `blog_categories_updated_at_idx` ON `blog_categories` (`updated_at`)",
  "CREATE INDEX `blog_posts_created_at_idx` ON `blog_posts` (`created_at`)",
  "CREATE INDEX `blog_posts_image_idx` ON `blog_posts` (`image_id`)",
  "CREATE INDEX `blog_posts_updated_at_idx` ON `blog_posts` (`updated_at`)",
  "CREATE INDEX `bloggers_created_at_idx` ON `bloggers` (`created_at`)",
  "CREATE INDEX `bloggers_image_idx` ON `bloggers` (`image_id`)",
  "CREATE INDEX `bloggers_updated_at_idx` ON `bloggers` (`updated_at`)",
  "CREATE INDEX `destinations_created_at_idx` ON `destinations` (`created_at`)",
  "CREATE INDEX `destinations_image_idx` ON `destinations` (`image_id`)",
  "CREATE UNIQUE INDEX `destinations_slug_idx` ON `destinations` (`slug`)",
  "CREATE INDEX `destinations_thumbnail_image_idx` ON `destinations` (`thumbnail_image_id`)",
  "CREATE INDEX `destinations_updated_at_idx` ON `destinations` (`updated_at`)",
  "CREATE INDEX `excursions_city_page_idx` ON `excursions` (`city_page_id`)",
  "CREATE INDEX `excursions_created_at_idx` ON `excursions` (`created_at`)",
  "CREATE INDEX `excursions_destination_image_idx` ON `excursions` (`destination_image_id`)",
  "CREATE INDEX `excursions_highlights_order_idx` ON `excursions_highlights` (`_order`)",
  "CREATE INDEX `excursions_highlights_parent_id_idx` ON `excursions_highlights` (`_parent_id`)",
  "CREATE INDEX `excursions_image_idx` ON `excursions` (`image_id`)",
  "CREATE INDEX `excursions_updated_at_idx` ON `excursions` (`updated_at`)",
  "CREATE INDEX `explore_banner_slides_created_at_idx` ON `explore_banner_slides` (`created_at`)",
  "CREATE INDEX `explore_banner_slides_image_idx` ON `explore_banner_slides` (`image_id`)",
  "CREATE INDEX `explore_banner_slides_updated_at_idx` ON `explore_banner_slides` (`updated_at`)",
  "CREATE INDEX `explore_listings_created_at_idx` ON `explore_listings` (`created_at`)",
  "CREATE INDEX `explore_listings_image_idx` ON `explore_listings` (`image_id`)",
  "CREATE INDEX `explore_listings_updated_at_idx` ON `explore_listings` (`updated_at`)",
  "CREATE INDEX `gallery_items_created_at_idx` ON `gallery_items` (`created_at`)",
  "CREATE INDEX `gallery_items_image_idx` ON `gallery_items` (`image_id`)",
  "CREATE INDEX `gallery_items_updated_at_idx` ON `gallery_items` (`updated_at`)",
  "CREATE INDEX `home_banner_slides_created_at_idx` ON `home_banner_slides` (`created_at`)",
  "CREATE INDEX `home_banner_slides_image_idx` ON `home_banner_slides` (`image_id`)",
  "CREATE INDEX `home_banner_slides_updated_at_idx` ON `home_banner_slides` (`updated_at`)",
  "CREATE INDEX `itineraries_banner_slides_created_at_idx` ON `itineraries_banner_slides` (`created_at`)",
  "CREATE INDEX `itineraries_banner_slides_image_idx` ON `itineraries_banner_slides` (`image_id`)",
  "CREATE INDEX `itineraries_banner_slides_updated_at_idx` ON `itineraries_banner_slides` (`updated_at`)",
  "CREATE INDEX `itineraries_created_at_idx` ON `itineraries` (`created_at`)",
  "CREATE INDEX `itineraries_gallery_image_idx` ON `itineraries_gallery` (`image_id`)",
  "CREATE INDEX `itineraries_gallery_order_idx` ON `itineraries_gallery` (`_order`)",
  "CREATE INDEX `itineraries_gallery_parent_id_idx` ON `itineraries_gallery` (`_parent_id`)",
  "CREATE INDEX `itineraries_image_idx` ON `itineraries` (`image_id`)",
  "CREATE INDEX `itineraries_inclusions_order_idx` ON `itineraries_inclusions` (`_order`)",
  "CREATE INDEX `itineraries_inclusions_parent_id_idx` ON `itineraries_inclusions` (`_parent_id`)",
  "CREATE INDEX `itineraries_itinerary_highlights_order_idx` ON `itineraries_itinerary_highlights` (`_order`)",
  "CREATE INDEX `itineraries_itinerary_highlights_parent_id_idx` ON `itineraries_itinerary_highlights` (`_parent_id`)",
  "CREATE INDEX `itineraries_itinerary_order_idx` ON `itineraries_itinerary` (`_order`)",
  "CREATE INDEX `itineraries_itinerary_parent_id_idx` ON `itineraries_itinerary` (`_parent_id`)",
  "CREATE UNIQUE INDEX `itineraries_slug_idx` ON `itineraries` (`slug`)",
  "CREATE INDEX `itineraries_updated_at_idx` ON `itineraries` (`updated_at`)",
  "CREATE INDEX `media_banners_background_image_idx` ON `media_banners` (`background_image_id`)",
  "CREATE INDEX `media_banners_created_at_idx` ON `media_banners` (`created_at`)",
  "CREATE INDEX `media_banners_slides_image_idx` ON `media_banners_slides` (`image_id`)",
  "CREATE INDEX `media_banners_slides_order_idx` ON `media_banners_slides` (`_order`)",
  "CREATE INDEX `media_banners_slides_parent_id_idx` ON `media_banners_slides` (`_parent_id`)",
  "CREATE INDEX `media_banners_updated_at_idx` ON `media_banners` (`updated_at`)",
  "CREATE INDEX `media_created_at_idx` ON `media` (`created_at`)",
  "CREATE UNIQUE INDEX `media_filename_idx` ON `media` (`filename`)",
  "CREATE INDEX `media_sizes_card_sizes_card_filename_idx` ON `media` (`sizes_card_filename`)",
  "CREATE INDEX `media_sizes_hero_sizes_hero_filename_idx` ON `media` (`sizes_hero_filename`)",
  "CREATE INDEX `media_sizes_thumbnail_sizes_thumbnail_filename_idx` ON `media` (`sizes_thumbnail_filename`)",
  "CREATE INDEX `media_updated_at_idx` ON `media` (`updated_at`)",
  "CREATE INDEX `package_banner_slides_created_at_idx` ON `package_banner_slides` (`created_at`)",
  "CREATE INDEX `package_banner_slides_image_idx` ON `package_banner_slides` (`image_id`)",
  "CREATE INDEX `package_banner_slides_updated_at_idx` ON `package_banner_slides` (`updated_at`)",
  "CREATE UNIQUE INDEX `payload_kv_key_idx` ON `payload_kv` (`key`)",
  "CREATE INDEX `payload_migrations_created_at_idx` ON `payload_migrations` (`created_at`)",
  "CREATE INDEX `payload_migrations_updated_at_idx` ON `payload_migrations` (`updated_at`)",
  "CREATE INDEX `payload_preferences_created_at_idx` ON `payload_preferences` (`created_at`)",
  "CREATE INDEX `payload_preferences_key_idx` ON `payload_preferences` (`key`)",
  "CREATE INDEX `payload_preferences_rels_order_idx` ON `payload_preferences_rels` (`order`)",
  "CREATE INDEX `payload_preferences_rels_parent_idx` ON `payload_preferences_rels` (`parent_id`)",
  "CREATE INDEX `payload_preferences_rels_path_idx` ON `payload_preferences_rels` (`path`)",
  "CREATE INDEX `payload_preferences_rels_users_id_idx` ON `payload_preferences_rels` (`users_id`)",
  "CREATE INDEX `payload_preferences_updated_at_idx` ON `payload_preferences` (`updated_at`)",
  "CREATE INDEX `testimonials_created_at_idx` ON `testimonials` (`created_at`)",
  "CREATE INDEX `testimonials_image_idx` ON `testimonials` (`image_id`)",
  "CREATE INDEX `testimonials_updated_at_idx` ON `testimonials` (`updated_at`)",
  "CREATE INDEX `tour_packages_created_at_idx` ON `tour_packages` (`created_at`)",
  "CREATE INDEX `tour_packages_image_idx` ON `tour_packages` (`image_id`)",
  "CREATE INDEX `tour_packages_updated_at_idx` ON `tour_packages` (`updated_at`)",
  "CREATE INDEX `users_created_at_idx` ON `users` (`created_at`)",
  "CREATE UNIQUE INDEX `users_email_idx` ON `users` (`email`)",
  "CREATE INDEX `users_sessions_order_idx` ON `users_sessions` (`_order`)",
  "CREATE INDEX `users_sessions_parent_id_idx` ON `users_sessions` (`_parent_id`)",
  "CREATE INDEX `users_updated_at_idx` ON `users` (`updated_at`)"
]
  for (const sql of statements) {
    if (sql) {
      try {
        await db.execute({ drizzle: db.drizzle, raw: sql })
      } catch (e) {
        // Ignore "already exists" errors
        if (!e.message?.includes('already exists')) throw e
      }
    }
  }
}

export async function down({ payload }) {}
